# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u5206\u7c7b', 'verbose_name_plural': '\u5206\u7c7b'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='owener',
            new_name='owner',
        ),
    ]
