# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.CharField(max_length=120, verbose_name='\u6587\u7ae0'),
        ),
    ]
